version: "3.8"

services:
  # Currency Converter Application
  currency-converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPEN_EXCHANGE_RATES_API_KEY=${OPEN_EXCHANGE_RATES_API_KEY}
      - OER_BASE_URL=${OER_BASE_URL:-https://openexchangerates.org/api}
    env_file:
      - .env.local
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/rates",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - currency-network

  # Development version (optional)
  currency-converter-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - OPEN_EXCHANGE_RATES_API_KEY=${OPEN_EXCHANGE_RATES_API_KEY}
      - OER_BASE_URL=${OER_BASE_URL:-https://openexchangerates.org/api}
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - currency-network

networks:
  currency-network:
    driver: bridge

volumes:
  node_modules:
